<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hotels = [
            // Marrakech Hotels
            ['name' => 'La Mamounia', 'city' => 'Marrakech', 'description' => 'A legendary palace hotel in the heart of Marrakech, offering luxurious accommodations and world-class amenities.', 'address' => 'Avenue Bab Jdid, Marrakech', 'price_per_night' => 450.00, 'rating' => 4.8, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking', 'Concierge']],
            ['name' => 'Royal Mansour', 'city' => 'Marrakech', 'description' => 'An exclusive riad-style hotel featuring traditional Moroccan architecture and modern luxury.', 'address' => 'Rue Abou Abbas El Sebti, Marrakech', 'price_per_night' => 600.00, 'rating' => 4.9, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Room Service']],
            ['name' => 'Four Seasons Resort', 'city' => 'Marrakech', 'description' => 'A stunning resort with beautiful gardens, multiple pools, and exceptional service.', 'address' => '1 Boulevard de la Menara, Marrakech', 'price_per_night' => 550.00, 'rating' => 4.7, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Parking']],
            ['name' => 'Riad Dar Anika', 'city' => 'Marrakech', 'description' => 'A charming riad in the medina with traditional decor and a beautiful rooftop terrace.', 'address' => '112 Riad Zitoun Jdid, Marrakech', 'price_per_night' => 180.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace', 'Room Service']],
            ['name' => 'Sofitel Marrakech', 'city' => 'Marrakech', 'description' => 'A luxury hotel combining French elegance with Moroccan charm.', 'address' => 'Rue Haroun Errachid, Marrakech', 'price_per_night' => 320.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym']],
            ['name' => 'Palais Namaskar', 'city' => 'Marrakech', 'description' => 'A contemporary luxury resort with stunning architecture and serene surroundings.', 'address' => 'Route de Bab Atlas, Marrakech', 'price_per_night' => 480.00, 'rating' => 4.7, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parking']],
            ['name' => 'Riad El Fenn', 'city' => 'Marrakech', 'description' => 'A boutique riad with artistic flair, located in the heart of the medina.', 'address' => 'Derb Moullay Abdullah Ben Hezzian, Marrakech', 'price_per_night' => 250.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Terrace']],
            ['name' => 'Amanjena', 'city' => 'Marrakech', 'description' => 'An exclusive resort offering privacy and tranquility in a beautiful setting.', 'address' => 'Route de Ouarzazate, Marrakech', 'price_per_night' => 700.00, 'rating' => 4.9, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Golf', 'Parking']],

            // Casablanca Hotels
            ['name' => 'Four Seasons Hotel', 'city' => 'Casablanca', 'description' => 'A modern luxury hotel in the heart of Casablanca with stunning ocean views.', 'address' => 'Boulevard de la Corniche, Casablanca', 'price_per_night' => 400.00, 'rating' => 4.7, 'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym']],
            ['name' => 'Hyatt Regency', 'city' => 'Casablanca', 'description' => 'A contemporary hotel offering comfort and convenience in the business district.', 'address' => 'Place des Nations Unies, Casablanca', 'price_per_night' => 280.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Business Center', 'Parking']],
            ['name' => 'Le Casablanca Hotel', 'city' => 'Casablanca', 'description' => 'A stylish hotel blending Art Deco design with modern amenities.', 'address' => '123 Boulevard Zerktouni, Casablanca', 'price_per_night' => 220.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Gym', 'Parking']],
            ['name' => 'Melliber Appart Hotel', 'city' => 'Casablanca', 'description' => 'Comfortable apartments with kitchen facilities, perfect for extended stays.', 'address' => 'Avenue Hassan II, Casablanca', 'price_per_night' => 150.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Kitchen', 'Pool', 'Parking']],
            ['name' => 'Sofitel Casablanca', 'city' => 'Casablanca', 'description' => 'A luxury hotel with elegant rooms and excellent service.', 'address' => 'Boulevard Zerktouni, Casablanca', 'price_per_night' => 300.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar']],
            ['name' => 'Kenzi Tower Hotel', 'city' => 'Casablanca', 'description' => 'A modern high-rise hotel with panoramic city views.', 'address' => 'Boulevard Mohammed Zerktouni, Casablanca', 'price_per_night' => 260.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Gym', 'Business Center']],
            ['name' => 'Hotel Le Doge', 'city' => 'Casablanca', 'description' => 'A boutique hotel with unique character and personalized service.', 'address' => '9 Rue Docteur Veyre, Casablanca', 'price_per_night' => 200.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Room Service']],

            // Rabat Hotels
            ['name' => 'Sofitel Rabat', 'city' => 'Rabat', 'description' => 'A luxury hotel overlooking the Atlantic Ocean with beautiful gardens.', 'address' => 'Boulevard des Nations Unies, Rabat', 'price_per_night' => 350.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Beach Access']],
            ['name' => 'Villa Mandarine', 'city' => 'Rabat', 'description' => 'A charming boutique hotel set in a beautiful garden with citrus trees.', 'address' => '19 Rue Ouled Bousbaa, Rabat', 'price_per_night' => 180.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Garden', 'Parking']],
            ['name' => 'Hotel La Tour Hassan', 'city' => 'Rabat', 'description' => 'A historic hotel in the heart of Rabat with traditional Moroccan architecture.', 'address' => '26 Avenue Chellah, Rabat', 'price_per_night' => 240.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Riad Kalaa', 'city' => 'Rabat', 'description' => 'A traditional riad in the medina with authentic Moroccan decor.', 'address' => 'Rue des Consuls, Rabat', 'price_per_night' => 120.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace', 'Room Service']],
            ['name' => 'Golden Tulip', 'city' => 'Rabat', 'description' => 'A modern hotel with comfortable rooms and excellent facilities.', 'address' => 'Avenue Fal Ould Oumeir, Rabat', 'price_per_night' => 200.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking']],

            // Tangier Hotels
            ['name' => 'El Minzah Hotel', 'city' => 'Tangier', 'description' => 'A historic hotel with colonial charm and stunning views of the Strait of Gibraltar.', 'address' => '85 Rue de la Liberté, Tangier', 'price_per_night' => 280.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Grand Hotel Villa de France', 'city' => 'Tangier', 'description' => 'A restored 19th-century hotel with elegant rooms and ocean views.', 'address' => '143 Rue d\'Angleterre, Tangier', 'price_per_night' => 320.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar']],
            ['name' => 'Hotel Rembrandt', 'city' => 'Tangier', 'description' => 'A comfortable hotel with modern amenities and friendly service.', 'address' => 'Boulevard Pasteur, Tangier', 'price_per_night' => 150.00, 'rating' => 4.1, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Nord Pinus Tanger', 'city' => 'Tangier', 'description' => 'A boutique hotel with artistic design and panoramic views.', 'address' => 'Avenue d\'Espagne, Tangier', 'price_per_night' => 250.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Terrace', 'Parking']],
            ['name' => 'Hotel Continental', 'city' => 'Tangier', 'description' => 'A historic hotel in the medina with traditional architecture.', 'address' => '36 Rue Dar Baroud, Tangier', 'price_per_night' => 100.00, 'rating' => 3.9, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace']],

            // Fes Hotels
            ['name' => 'Riad Fes', 'city' => 'Fes', 'description' => 'A luxurious riad in the heart of the medina with beautiful courtyards.', 'address' => '5 Derb Ben Slimane Zerhoun, Fes', 'price_per_night' => 300.00, 'rating' => 4.7, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Terrace']],
            ['name' => 'Palais Faraj', 'city' => 'Fes', 'description' => 'A stunning palace hotel with panoramic views of the medina.', 'address' => 'Bab Ziat, Fes', 'price_per_night' => 380.00, 'rating' => 4.8, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Karawan Riad', 'city' => 'Fes', 'description' => 'A charming riad with traditional decor and excellent service.', 'address' => '33 Derb Sidi Boujida, Fes', 'price_per_night' => 180.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace', 'Room Service']],
            ['name' => 'Dar Bensouda', 'city' => 'Fes', 'description' => 'A beautifully restored riad offering authentic Moroccan hospitality.', 'address' => '14 Derb Bensouda, Fes', 'price_per_night' => 200.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Terrace']],
            ['name' => 'Hotel Sahrai', 'city' => 'Fes', 'description' => 'A modern luxury hotel with stunning views and world-class amenities.', 'address' => 'Avenue des F.A.R, Fes', 'price_per_night' => 420.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Gym']],

            // Agadir Hotels
            ['name' => 'Sofitel Agadir', 'city' => 'Agadir', 'description' => 'A beachfront resort with direct access to the sandy beach.', 'address' => 'Baie des Palmiers, Agadir', 'price_per_night' => 350.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Beach Access', 'Bar']],
            ['name' => 'Hyatt Place', 'city' => 'Agadir', 'description' => 'A modern hotel with comfortable rooms and excellent facilities.', 'address' => 'Boulevard du 20 Août, Agadir', 'price_per_night' => 220.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking']],
            ['name' => 'Riad Villa Blanche', 'city' => 'Agadir', 'description' => 'A peaceful riad with beautiful gardens and a relaxing atmosphere.', 'address' => 'Hay Mohammadi, Agadir', 'price_per_night' => 150.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Garden', 'Parking']],
            ['name' => 'Hotel Tikida Beach', 'city' => 'Agadir', 'description' => 'A beachfront hotel with multiple pools and entertainment facilities.', 'address' => 'Boulevard du 20 Août, Agadir', 'price_per_night' => 180.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Beach Access', 'Entertainment']],
            ['name' => 'Atlas Amadil Beach', 'city' => 'Agadir', 'description' => 'An all-inclusive resort with beautiful beachfront location.', 'address' => 'Boulevard du 20 Août, Agadir', 'price_per_night' => 200.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Beach Access', 'All-Inclusive']],

            // Meknes Hotels
            ['name' => 'Riad Yacout', 'city' => 'Meknes', 'description' => 'A traditional riad in the medina with authentic Moroccan architecture.', 'address' => '79 Derb Hamri, Meknes', 'price_per_night' => 120.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace', 'Room Service']],
            ['name' => 'Hotel Transatlantique', 'city' => 'Meknes', 'description' => 'A historic hotel with colonial charm and modern amenities.', 'address' => 'Avenue Allal Ben Abdellah, Meknes', 'price_per_night' => 140.00, 'rating' => 4.1, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Dar Zitoun', 'city' => 'Meknes', 'description' => 'A charming guesthouse with traditional decor and warm hospitality.', 'address' => 'Rue Dar Smen, Meknes', 'price_per_night' => 100.00, 'rating' => 4.0, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace']],

            // Ouarzazate Hotels
            ['name' => 'Berbere Palace', 'city' => 'Ouarzazate', 'description' => 'A beautiful hotel with stunning views of the Atlas Mountains.', 'address' => 'Avenue Mohammed V, Ouarzazate', 'price_per_night' => 160.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Le Temple des Arts', 'city' => 'Ouarzazate', 'description' => 'A unique hotel celebrating the film industry with themed rooms.', 'address' => 'Route de Marrakech, Ouarzazate', 'price_per_night' => 180.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Bar', 'Gym']],
            ['name' => 'Dar Chamaa', 'city' => 'Ouarzazate', 'description' => 'A traditional kasbah-style hotel with authentic Berber architecture.', 'address' => 'Route de Skoura, Ouarzazate', 'price_per_night' => 130.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace', 'Parking']],

            // Additional hotels to reach 50
            ['name' => 'Riad Dar Zaman', 'city' => 'Marrakech', 'description' => 'A peaceful riad with beautiful courtyards and traditional architecture.', 'address' => 'Derb Sidi Bouamar, Marrakech', 'price_per_night' => 160.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Terrace']],
            ['name' => 'Hotel Les Jardins de la Koutoubia', 'city' => 'Marrakech', 'description' => 'A luxury hotel with beautiful gardens and views of the Koutoubia Mosque.', 'address' => '26 Rue de la Koutoubia, Marrakech', 'price_per_night' => 320.00, 'rating' => 4.6, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar']],
            ['name' => 'Riad Kniza', 'city' => 'Marrakech', 'description' => 'An elegant riad with antique furnishings and personalized service.', 'address' => '34 Derb l\'Hotel, Marrakech', 'price_per_night' => 220.00, 'rating' => 4.5, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Terrace', 'Room Service']],
            ['name' => 'Hotel Kenzi Menara Palace', 'city' => 'Marrakech', 'description' => 'A modern hotel with excellent facilities and convenient location.', 'address' => 'Avenue de France, Marrakech', 'price_per_night' => 200.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Gym', 'Parking']],
            ['name' => 'Riad Al Badia', 'city' => 'Marrakech', 'description' => 'A charming riad with traditional decor and a beautiful rooftop terrace.', 'address' => '15 Derb Sidi Lahcen Ouali, Marrakech', 'price_per_night' => 140.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace']],
            ['name' => 'Hotel Atlas Asni', 'city' => 'Casablanca', 'description' => 'A comfortable hotel with modern amenities and friendly staff.', 'address' => 'Boulevard Zerktouni, Casablanca', 'price_per_night' => 170.00, 'rating' => 4.1, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Hotel Barcelo', 'city' => 'Casablanca', 'description' => 'A contemporary hotel with stylish rooms and excellent service.', 'address' => 'Place des Nations Unies, Casablanca', 'price_per_night' => 240.00, 'rating' => 4.4, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Gym', 'Business Center']],
            ['name' => 'Riad Dar Bensouda', 'city' => 'Rabat', 'description' => 'A traditional riad with beautiful courtyards and traditional decor.', 'address' => 'Rue des Consuls, Rabat', 'price_per_night' => 130.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace']],
            ['name' => 'Hotel Farah Rabat', 'city' => 'Rabat', 'description' => 'A modern hotel with comfortable rooms and good facilities.', 'address' => 'Avenue des F.A.R, Rabat', 'price_per_night' => 190.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Bar', 'Parking']],
            ['name' => 'Hotel Riad Salam', 'city' => 'Fes', 'description' => 'A comfortable hotel with traditional Moroccan design.', 'address' => 'Boulevard Zerktouni, Fes', 'price_per_night' => 160.00, 'rating' => 4.2, 'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Pool', 'Restaurant', 'Parking']],
            ['name' => 'Riad Tafilalet', 'city' => 'Fes', 'description' => 'A charming riad with authentic decor and warm hospitality.', 'address' => 'Derb Sidi Ahmed, Fes', 'price_per_night' => 140.00, 'rating' => 4.3, 'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop', 'amenities' => ['WiFi', 'Restaurant', 'Terrace']],
        ];

        foreach ($hotels as $hotel) {
            Hotel::create($hotel);
        }
    }
}
